### PR TITLE
Data vis

### PR DESCRIPTION
**Pull request by Maximellerbach**
Added a bunch of data visualization functions with some tests.
note: as the github action is headless (no graphical interface), those tests are not run in github, but you can still run them using:
```bash
pytest autopylot/ 
```
If you want ONLY vis tests: 
```bash
pytest autopylot/ -m "vis" 
```
If you DON'T want vis tests:
```bash
pytest autopylot/ -m "not vis" 
```

### CODE REVIEW

**Comment by Maximellerbach** [comment]
Ready for review !

**Comment by DieuCrevette** [comment]
image
Elle sert a quoi la boucle while ici ?

**Review by DieuCrevette — APPROVED** [review]
I have just one question on the one of the vis.py function

**Comment by Maximellerbach** [comment]
> image Elle sert a quoi la boucle while ici ?

elle sert à eviter les conflits entre lecture / écriture depuis plusieurs thread.

**Pull request merged**
